<a href="https://colab.research.google.com/github/030108ming/deep-learning-with-pytorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**


*  Add ,Subtract, Multiply, Divide REmainders, Exponents
*  shorthand and longhand
*  Reassignment




In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
# subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
# sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [8]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# MUl longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
# division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
# Div longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# Remainders modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
# Remainder longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [15]:
# Exponent / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [16]:
# another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [17]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [18]:
tensor_a

tensor([1, 2, 3, 4])

In [24]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
tensor_a

tensor([ 6,  8, 10, 12])