<a href="https://colab.research.google.com/github/030108ming/deep-learning-with-pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS


*   A torch.
*   Similar To Numpy Arrays, but full of things that make them work better on GPUS


*   default data type of float 32
*   More suitaable for deep learning than a Numpy array





In [1]:
import torch

In [2]:
import  numpy as np

*LISTS

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

 **NUMPY ARRAY**

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.54202218, 0.75724098, 0.50496613, 0.38548902],
       [0.79822299, 0.76240605, 0.29932873, 0.1406028 ],
       [0.99932068, 0.51534999, 0.93043634, 0.50246719]])

In [6]:
np1.dtype

dtype('float64')

***TENSORS***

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.0586, -0.8871, -0.8037, -0.5363],
        [ 0.2028, -0.2915, -0.7898, -1.7649],
        [-1.5774, -0.0343, -1.7209, -1.0426]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5420, 0.7572, 0.5050, 0.3855],
        [0.7982, 0.7624, 0.2993, 0.1406],
        [0.9993, 0.5153, 0.9304, 0.5025]], dtype=torch.float64)